### ISSUE TITLE
USER STORY: View Recipeslist

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#20]
EPIC: Recipe Interaction

As a **Site User** I can **view a list of recipes** so that **I can select one to read**

**Acceptance Criteria**

- When the user choose a specific recipes category, the recipe page will shown with a list of recipes.
- Each recipe should appear as a card showing the recipe image, title and cook time.

**Tasks**

- [x] Create a link for Recipe Category on the Navbar which only displays the recipes within this category.
- [x] Create HTML template for recipe category.
- [x] Develop a user-friendly recipe card layout using bootstrap cards.
- [x] Create View for recipeslist using Django.
