### ISSUE TITLE
USER STORY: Add bookmark

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#24]
EPIC: Recipe Interaction

As a **Site User** I can **bookmark recipe** so that **I can save it in my profile**

**Acceptance Criteria**
- When a user is logged in, a bookmark icon should display underneath the recipe detail page.
- When the user clicks on the bookmark  icon it should change to a solid bookmark and the recipe should be added to the user's bookmarks page (Profile).
- When the user clicks on the solid bookmark it should change to an outline bookmark and the recipe should be removed from the user's bookmarks page.
- The user should be notified that the recipe was successfully added/removed from their bookmarks.

**Tasks**
- [x] Add a bookmark Icon on the recipe detail page that only appears when the user is logged in.
- [x]  Change bookmark icon to solid when user had bookmarked it.
- [x] Add View functionalty.
