### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#26]
EPIC: User Profile

As a **Site User** I can **register an account** so that **I can comment and like**

**Acceptance Criteria**
-  A signup button should be visible on the navbar.
-  When user click the button  should be taken to the signup page.
-  When user enter details and click submit a new account should be created for.

**Tasks**

- [x]  Install allauth and add to installed apps.
- [x]  Add allauth urls.
- [x]  Add sign up link to navbar
- [x]  Customise allauth sign up HTML templates
