### ISSUE TITLE
USER STORY: Log in / out

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#27]
EPIC:User Profile

As a **Site User** I can **log in/ out** so that **I keep my account secure**

**Acceptance Criteria**
_Acceptance Criteria logged in user_
-  When user click the log out button should be asked to confirm logging out.
-  After user confirm logging out  should be notified that he has been logged out successfully.  

 _Acceptance Criteria logged-out user_
-  Log in button should be visible on the home page and on the nav bar.
-  When user enter username and password and click sign in button, user should be logged in.
-  User should be notified that has been logged in successfully.
-  If user enter the incorrect information, a feedback should be shown to notify the user to enter correct details.

**Tasks**
- [x]  Install allauth and add to installed apps.
- [x] Add allauth urls.
- [x] Add log in and log out links to navbar
- [x] Customise allauth login, logout HTML templates
- [x] Create confirmation messages for successful login/logout
