### ISSUE TITLE
USER STORY: View Bookmarked recipes

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#28]
EPIC: User Profile

As a **Logged-in User** I can **view my bookmarked recipes in my profile** so that **I can find them easily each time I need them**

**Acceptance Criteria**

-  Logged-in user can see  'profile' link in the navbar
- After the user click on it , the user will navigate to profile page
- This page show a list of recipes that the user bookmarked
- Each recipe should appear as a card as it in the recipe list page
- When the user click on recipe, user move to recipe details page

**Tasks**

- [x] Create a button for Profile recipes on the Navbar which only displays when the user is logged in.
- [x] Create HTML template for Profile page.
- [x] Create View for Profile using Django.
- [x] Add the appropriate urls
