### ISSUE TITLE
USER STORY: Approve Comments

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#32]
EPIC: Site Management

As a **Site Admin** I can **approve or disapprove comments** so that **I can filter out objectionable comments**

**Acceptance Criteria**
- When logged-in user leave a comment and click on submit button, message with 'comment is waiting approval' will appear   
- Admin should approve this comment from admin panel as to be shown by other users
**Tasks**
- [x] Design a Comment model 
- [x] Design comment form
- [x] Create comment form class and implement functionality
- [x] Set approve value to True from admin panel
