### ISSUE TITLE
USER STORY: View My Published Recipes

### ISSUE THREAD

**Issue by AlaYousef** [AlaYousef/portfolio-project4#36]
EPIC:User Profile

As a **Site User** I can **view my published recipes** so that **I can manage all my added recipes from my profile**

**Acceptance Criteria**

- A link for profile dropdown menu should be shown in navbar for logged-in user.
- Logged-in user can see my recipes link from the dropdown menu
- The user will redirect to my recipe page 
- The recipes should displayed as a list of recipes cards
- Each recipe can update and delete by the user

**Tasks**

- [x] Create myrecipe view 
- [x] Add appropriate url to urls.py
- [x] Create  an intutive template to display the recipes
- [x] Create edit, delete views with appropriate methods
- [x] Add appropriate ursl to urls.py
- [x] Create  edit_recipe.html, delete_recipe.html templates.
